// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnKsQ30EAEy9FdJL4Cxt6IlNfMMWWieA8',
    appId: '1:672520110700:web:13bc9a9fbde8a3c83b8e49',
    messagingSenderId: '672520110700',
    projectId: 'hopedrop-e673b',
    authDomain: 'hopedrop-e673b.firebaseapp.com',
    storageBucket: 'hopedrop-e673b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwOZlqy-EeayUXc1u1_Ji1-Ts3iVczTLY',
    appId: '1:672520110700:android:2723865d6f1ff2163b8e49',
    messagingSenderId: '672520110700',
    projectId: 'hopedrop-e673b',
    storageBucket: 'hopedrop-e673b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8yWfGSoZ_mmBmfARQBPymJKoi3wfsmAo',
    appId: '1:672520110700:ios:f81170c223601a563b8e49',
    messagingSenderId: '672520110700',
    projectId: 'hopedrop-e673b',
    storageBucket: 'hopedrop-e673b.firebasestorage.app',
    androidClientId: '672520110700-3uorc5juvgo1pgu8f344p8mtig2b005o.apps.googleusercontent.com',
    iosClientId: '672520110700-mas2f8bqtrgsea70cqqv9oesudhkicin.apps.googleusercontent.com',
    iosBundleId: 'com.example.hopedrop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8yWfGSoZ_mmBmfARQBPymJKoi3wfsmAo',
    appId: '1:672520110700:ios:f81170c223601a563b8e49',
    messagingSenderId: '672520110700',
    projectId: 'hopedrop-e673b',
    storageBucket: 'hopedrop-e673b.firebasestorage.app',
    androidClientId: '672520110700-3uorc5juvgo1pgu8f344p8mtig2b005o.apps.googleusercontent.com',
    iosClientId: '672520110700-mas2f8bqtrgsea70cqqv9oesudhkicin.apps.googleusercontent.com',
    iosBundleId: 'com.example.hopedrop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnKsQ30EAEy9FdJL4Cxt6IlNfMMWWieA8',
    appId: '1:672520110700:web:9ff9e9a4207657f63b8e49',
    messagingSenderId: '672520110700',
    projectId: 'hopedrop-e673b',
    authDomain: 'hopedrop-e673b.firebaseapp.com',
    storageBucket: 'hopedrop-e673b.firebasestorage.app',
  );
}
